### ISSUE TITLE
renderPrePassMgr

### ISSUE THREAD

**Issue by ghost** [Azaezel/Torque3D#26]
Hi, Thank you very much for these contributions, they are trully asesome!!!
i've found PBR branch has some issues:

getPrePassMat() is not member of TerrainCellMaterial
MRTLightmapsDuringPrePass is not member of AdvancedLightBinManager
PrePassBin is not member of SceneData
Some MFT_DeferredEmptySpec identifies are undefined. 

Are you performing some lighting prepass in final full deferred rendering scheme?

ps: sorry, i've just a newbie in t3d

**Comment by Azaezel** [comment]
we recently shifted things over nomenclature wise from prepass to deferred to reflect whats actually going on better. might have missed a few spots. will crosscheck.

**Comment by Azaezel** [comment]
yeah, just did a fresh checkout. crosscheck against: https://github.com/Azaezel/Torque3D/commit/2ed8290116828bc04c29432befae8617663c6c78

**Comment by luchete80** [comment]
Thank you very much!! I'll try with this commit so.
I've ask you some question about gbuffer packing:
http://forums.torque3d.org/viewtopic.php?f=9&t=55&p=6188#p6188
